<?php $conn = new mysqli('db558054145.db.1and1.com', 'dbo558054145', 'fender123', 'db558054145'); if ($conn->connect_error) { die("connection failed:" . $conn->connect_error); } $sql = '';
 $sql .= "CREATE TABLE ArbysClean (`restName` varchar(30) COLLATE latin1_general_ci NOT NULL DEFAULT 'ArbysClean', `High Protein` int(1) DEFAULT '0',     `Gluten Free` tinyint(1) DEFAULT '0', `Low Calorie` tinyint(1) DEFAULT '0', `Low Carbs` tinyint(1) DEFAULT '0',`mealName` varchar(50) COLLATE latin1_general_ci NOT NULL, `mealDesc` varchar(100) COLLATE latin1_general_ci DEFAULT NULL, `nutrFat` int(11), `nutrSatFat` int(11), `nutrChol` int(11), `nutrSodium` int(11), `nutrCarb` int(11), `nutrFiber` int(11), `nutrSugar` int(11), `nutrProtein` int(11), `nutrCal` int(11), `mealRating` int(11) DEFAULT NULL, `time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '1', '1', '0', 'Regular Roast Beef', 'Good protein to calorie ratio. Low calorie meal. Fat percentage is a bit high. Carbohdryate percentage is not bad. ', '14', '5', '44', '953', '34', '2', '5', '21', '320', '13'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '0', '1', '0', 'Curly Fries', 'Bad protein to calorie ratio. Low calorie meal. Fat percentage is high. ', '22', '3', '0', '900', '46', '5', '0', '5', '400', '9'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '0', '1', '0', 'Beef N Cheddar Classic', 'Low calorie meal. Fat percentage is a bit high. Carbohdryate percentage is not bad. High in sodium. ', '20', '6', '60', '1310', '45', '2', '9', '24', '450', '9'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '1', '1', '0', 'Medium Roast Beef Sandwich', 'Good protein to calorie ratio! Low calorie meal. Fat percentage is not bad. High in sodium. ', '16', '5', '61', '1295', '47', '2', '6', '31', '415', '13'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '1', '1', '0', 'Santa Fe Salad w/ Grilled Chicken', 'Great protein to calorie ratio! Low calorie meal. Fat percentage is not bad. Carbohdryate percentage is low. ', '11', '6', '78', '621', '21', '6', '8', '30', '305', '20'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '1', '1', '0', 'Marthas Vineyard Salad', 'Great protein to calorie ratio! Low calorie. Fat percentage is great. Carbohdryate percentage is great! ', '8', '4', '72', '454', '24', '5', '17', '26', '277', '25'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '0', '1', '0', 'ArbysClean Melt', 'Low calorie meal. Fat percentage is not bad. ', '12', '4', '30', '921', '36', '2', '5', '16', '302', '14'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '1', '1', '0', 'Roast Beef Classic', 'Good protein to calorie ratio. Low calorie meal. Fat percentage is not bad. Carbohdryate percentage is not bad. High in sodium. ', '14', '5', '60', '1150', '38', '1', '8', '23', '375', '13'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '0', '0', '0', 'Roast Turkey and Swiss Sandwich', 'Fat percentage is a bit high. Very high in sodium! ', '28', '7', '75', '1760', '77', '5', '18', '39', '700', '3'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '1', '1', '0', 'French Dip Sub w/ Au Jus', 'Good protein to calorie ratio. Low calorie meal. Fat percentage is not bad. Carbohdryate percentage is not bad. Very high in sodium! ', '17', '7', '59', '2803', '48', '2', '3', '29', '448', '12'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '0', '1', '0', 'Kids Meal - Junior Roast Beef Sandwich', 'Low calorie. Fat percentage is not bad. ', '10', '4', '29', '740', '34', '2', '5', '16', '272', '14'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '0', '1', '0', 'Mozzarella Sticks', 'Not a good protein to calorie ratio. Low calorie meal. Fat percentage is high. Carbohdryate percentage is great! Very high in sodium! ', '18', '7', '42', '1511', '31', '2', '5', '18', '365', '10'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '1', '1', '0', 'Ham &amp; Swiss Melt Sandwich', 'Good protein to calorie ratio. Low calorie. High in sodium. ', '6', '2', '27', '1118', '35', '1', '6', '18', '275', '12'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '0', '0', '0', 'Roast Turkey Ranch &amp; Bacon Sandwich', 'Pretty high in calories. Fat percentage is a bit high. Carbohdryate percentage is great! Very high in sodium! ', '38', '11', '109', '2258', '75', '5', '17', '49', '834', '5'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '1', '1', '0', 'Chicken Tenders', 'Good protein to calorie ratio. Low calorie meal. Fat percentage is high. Carbohdryate percentage is good. High in sodium. ', '21', '3', '48', '1361', '32', '2', '0', '28', '434', '12'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '1', '0', '0', 'Chicken Club Salad', 'Good protein to calorie ratio. Fat percentage is high. Carbohdryate percentage is low. High in sodium. ', '26', '8', '209', '1235', '32', '5', '4', '33', '504', '10'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '1', '1', '0', 'Chicken Fillet Sandwich - Grilled', 'Good protein to calorie ratio! Low calorie meal. Fat percentage is a bit high. Carbohdryate percentage is great! ', '17', '3', '9', '913', '36', '3', '7', '32', '414', '17'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '0', '1', '0', 'Super Roast Beef', 'Low calorie meal. Fat percentage is a bit high. Carbohdryate percentage is not bad. High in sodium. ', '19', '6', '44', '1060', '40', '2', '10', '21', '398', '10'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '0', '0', '0', 'Corned Beef Reuben Sandwich', 'Fat percentage is a bit high. Carbohdryate percentage is good. Very high in sodium! ', '30', '8', '55', '1610', '62', '4', '7', '32', '640', '8'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '0', '1', '0', 'Roast Beef Sandwich', 'Low calorie meal. Fat percentage is perfect! ', '8', '2', '36', '782', '36', '1', '4', '17', '304', '17'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '1', '0', '0', 'Large Roast Beef Sandwich', 'Good protein to calorie ratio! Fat percentage is high. Carbohdryate percentage is good. High in saturated fat! Very high in sodium! ', '28', '12', '102', '1869', '41', '3', '6', '42', '547', '7'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '0', '0', '0', 'Chicken Salad w/ Pecans Wrap', 'Not a good protein to calorie ratio. Very high percentage of fat. Carbohdryate percentage is good. High in sodium. ', '38', '10', '74', '1199', '48', '8', '3', '30', '638', '6'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '0', '1', '0', 'Homestyle Fries', 'Low calorie meal. Very high percentage of fat. Lots of carbohdyrates. ', '20', '4', '0', '549', '44', '3', '1', '3', '302', '3'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '0', '0', '0', 'Italian Sub', 'Bad protein to calorie ratio. Fat percentage is high. Carbohdryate percentage is good. Very high in sodium! ', '33', '7', '51', '1986', '48', '3', '6', '24', '622', '3'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '0', '0', '0', 'Chicken Bacon &amp; Swiss - Crispy', 'Fat percentage is a bit high. Carbohdryate percentage is great! High in sodium. ', '29', '7', '68', '1320', '52', '2', '13', '36', '624', '9'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '0', '1', '0', 'French Dip &amp; Swiss Sandwich', 'Low calorie meal. Fat percentage is not bad. Very high in sodium! ', '17', '8', '70', '2140', '50', '2', '3', '26', '450', '10'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '0', '1', '0', 'Wrap, Wheat Tortilla', 'Not a good protein to calorie ratio. Low calorie. Fat percentage is perfect! Carbohdryate percentage is high. ', '6', '1', '0', '620', '38', '3', '0', '10', '230', '14'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '0', '1', '0', 'Butter &amp; Sour Cream Baked Potato', 'Bad protein to calorie ratio. Low calorie meal. Fat percentage is high. Carbohdryate percentage is a little high. High in saturated fat! Low in sodium. ', '24', '15', '56', '167', '65', '6', '0', '8', '495', '4'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '0', '1', '0', 'Ham &amp; Cheese Croissant', 'Not a good protein to calorie ratio. Low calorie. Fat percentage is a bit high. Carbohdryate percentage is great! ', '12', '7', '53', '842', '22', '1', '3', '13', '274', '14'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '1', '0', '0', 'Roast Turkey Ranch &amp; Bacon Wrap', 'Good protein to calorie ratio. Fat percentage is high. Carbohdryate percentage is low. Very high in sodium! ', '37', '11', '109', '2215', '44', '4', '3', '49', '700', '3'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '1', '1', '0', 'Chicken Bacon &amp; Swiss - Grilled', 'Great protein to calorie ratio! Low calorie meal. Fat percentage is not bad. Carbohdryate percentage is great! High in sodium. ', '17', '4', '25', '1333', '38', '2', '9', '38', '462', '18'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '0', '1', '1', 'Potato Cakes', 'Calories are very low. Very high percentage of fat. Carbohdryate percentage is not bad. Low in sodium. ', '9', '1', '0', '196', '13', '1', '0', '1', '123', '11'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '1', '1', '1', 'Chicken Fingers Natural', 'Good protein to calorie ratio. Calories are very low. Fat percentage is high. Carbohdryate percentage is good. ', '7', '1', '16', '454', '11', '1', '0', '10', '145', '16'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '1', '1', '0', 'Hot Ham n Cheese', 'Good protein to calorie ratio! Low calorie meal. High in sodium. ', '7', '2', '35', '1420', '35', '1', '7', '23', '304', '13'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '0', '1', '0', 'Loaded Potato Bites', 'Bad protein to calorie ratio. Low calorie meal. Very high percentage of fat. Carbohdryate percentage is good. ', '22', '7', '13', '800', '27', '2', '0', '11', '353', '8'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '1', '1', '0', 'French Dip Sandwich', 'Good protein to calorie ratio. Low calorie meal. Fat percentage is a bit high. Carbohdryate percentage is good. High in sodium. ', '16', '6', '58', '1282', '37', '3', '2', '26', '391', '13'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '0', '0', '0', 'Fish Sandwich', 'Bad protein to calorie ratio. Fat percentage is a bit high. High in sodium. ', '25', '4', '45', '1010', '64', '2', '9', '21', '570', '5'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '1', '1', '0', 'Market Fresh Mini Turkey &amp; Cheese Sandwich', 'Good protein to calorie ratio! Low calorie. ', '4', '1', '33', '798', '28', '2', '6', '17', '235', '16'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '1', '1', '0', 'Santa Fe Salad', 'Good protein to calorie ratio. Low calorie meal. Fat percentage is a bit high. Carbohdryate percentage is great! High in sodium. ', '23', '8', '59', '1231', '42', '7', '6', '30', '499', '16'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '1', '0', '0', 'Roast Turkey Reuben Sandwich', 'Good protein to calorie ratio! Fat percentage is high. Carbohdryate percentage is good. High in sodium. ', '30', '8', '94', '1429', '56', '3', '6', '44', '611', '9'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '0', '0', '0', 'Philly Beef &amp; Swiss Sub', 'Under 700 calories. Fat percentage is high. Carbohdryate percentage is low. Very high in sodium! ', '35', '11', '90', '1942', '46', '4', '5', '36', '670', '3'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '0', '0', '0', 'Broccoli &amp; Cheese Baked Potato', 'Bad protein to calorie ratio. Fat percentage is a bit high. Carbohdryate percentage is a little high. ', '22', '11', '48', '784', '73', '8', '1', '12', '535', '4'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '1', '1', '0', 'Chicken Cordon Bleu Sandwich - Grilled', 'Great protein to calorie ratio! Low calorie meal. Fat percentage is not bad. Carbohdryate percentage is good. Very high in sodium! ', '19', '4', '32', '1561', '35', '2', '7', '42', '488', '16'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '0', '1', '1', 'Raspberry Vinaigrette', 'Calories are very low. Very high percentage of fat. Carbohdryate percentage is good. ', '14', '2', '0', '387', '18', '0', '16', '0', '194', '4'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '1', '1', '0', 'Jr. Ham &amp; Swiss Melt', 'Good protein to calorie ratio. Low calorie. Carbohdryate percentage is not bad. ', '5', '1', '23', '873', '23', '1', '5', '14', '211', '15'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '1', '0', '0', 'SW Chipotle Chicken Sandwich - Grilled', 'Good protein to calorie ratio! Fat percentage is high. Carbohdryate percentage is good. High in sodium. ', '25', '8', '34', '1241', '37', '3', '7', '39', '517', '10'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '0', '1', '0', 'Cherry Turnover', 'Bad protein to calorie ratio. Low calorie. Fat percentage is high. Lots of carbohdyrates. ', '13', '3', '0', '201', '35', '2', '15', '4', '247', '1'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '0', '1', '0', 'Apple Turnover', 'Bad protein to calorie ratio. Low calorie. Fat percentage is high. Lots of carbohdyrates. ', '14', '4', '0', '201', '35', '2', '15', '4', '247', '1'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '0', '1', '0', 'Hot Ham &amp; Swiss Sub', 'Low calorie meal. Fat percentage is not bad. Carbohdryate percentage is good. Very high in sodium! ', '18', '4', '55', '1826', '45', '3', '6', '29', '498', '13'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '0', '0', '0', 'Bacon Beef n Cheddar Sandwich', 'Fat percentage is high. Carbohdryate percentage is great! Very high in sodium! ', '27', '9', '64', '1573', '45', '2', '9', '27', '521', '7'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '0', '1', '0', 'Sourdough Roast Beef Melt', 'Low calorie meal. Fat percentage is not bad. High in sodium. ', '14', '5', '30', '1047', '40', '2', '4', '18', '355', '12'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '0', '1', '0', 'Jalapeno Bites', 'Bad protein to calorie ratio. Low calorie meal. Very high percentage of fat. Carbohdryate percentage is good. ', '21', '9', '28', '526', '29', '2', '3', '5', '305', '4'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '0', '0', '0', 'Chicken Fillet Sandwich - Crispy', 'Fat percentage is high. Carbohdryate percentage is great! ', '30', '5', '52', '901', '50', '3', '11', '30', '576', '10'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '0', '0', '0', 'Ultimate BLT Wrap', 'Bad protein to calorie ratio. Very high percentage of fat. Carbohdryate percentage is low. Very high in sodium! ', '44', '11', '51', '1530', '45', '5', '4', '23', '648', '2'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '1', '0', '0', 'Chicken Cordon Bleu Sandwich - Crispy', 'Good protein to calorie ratio. Fat percentage is a bit high. Carbohdryate percentage is good. Very high in sodium! ', '31', '6', '74', '1548', '49', '2', '11', '40', '650', '8'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '0', '0', '0', 'Bacon, Egg, &amp; Cheese Wrap', 'Bad protein to calorie ratio. Very high percentage of fat. Carbohdryate percentage is good. High in sodium. ', '39', '8', '165', '1367', '50', '2', '2', '16', '515', '3'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '1', '0', '0', 'Southwest Chicken Wrap', 'Good protein to calorie ratio. Fat percentage is high. Carbohdryate percentage is good. Very high in sodium! ', '29', '9', '88', '1545', '42', '4', '3', '36', '567', '7'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '0', '0', '0', 'Turkey Sub', 'Fat percentage is a bit high. Carbohdryate percentage is good. Very high in sodium! ', '30', '6', '75', '2029', '47', '3', '5', '35', '633', '8'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '0', '1', '1', 'Light Buttermilk Ranch Dressing', 'Calories are very low. Fat percentage is high. ', '6', '1', '1', '472', '13', '1', '5', '1', '112', '10'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '0', '1', '0', 'Onion Petals', 'Bad protein to calorie ratio. Low calorie meal. Very high percentage of fat. Carbohdryate percentage is not bad. ', '23', '4', '1', '332', '35', '2', '7', '4', '331', '6'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '0', '1', '0', 'Croissant', 'Bad protein to calorie ratio. Calories are very low. Fat percentage is high. Low in sodium. ', '10', '6', '30', '190', '21', '1', '2', '3', '190', '7'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '0', '1', '0', 'Chicken Biscuit', 'Bad protein to calorie ratio. Low calorie meal. Fat percentage is high. Carbohdryate percentage is good. High in sodium. ', '23', '5', '17', '1240', '39', '1', '3', '15', '417', '5'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '0', '1', '0', 'Bacon, Egg &amp; Cheese Croissant', 'Bad protein to calorie ratio. Low calorie meal. Very high percentage of fat. Carbohdryate percentage is low. ', '22', '10', '198', '850', '23', '1', '3', '14', '378', '4'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '0', '1', '0', 'Curly Fries', 'Bad protein to calorie ratio. Low calorie meal. Fat percentage is high. ', '22', '3', '0', '920', '48', '5', '0', '5', '410', '8'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '0', '1', '0', 'Biscuit, breakfast', 'Bad protein to calorie ratio. Low calorie. Fat percentage is high. Carbohdryate percentage is not bad. ', '15', '3', '1', '786', '28', '1', '3', '5', '273', '7'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '0', '0', '0', 'Deluxe Baked Potato', 'Bad protein to calorie ratio. Fat percentage is high. Carbohdryate percentage is not bad. High in saturated fat! ', '32', '19', '91', '346', '67', '6', '0', '20', '645', '5'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '0', '0', '0', 'SW Chipotle Chicken Sandwich - Crispy', 'Under 700 calories. Fat percentage is high. Carbohdryate percentage is good. High in sodium. ', '37', '10', '77', '1228', '51', '3', '11', '38', '680', '4'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '1', '1', '0', 'Kids Meal - Chicken Tenders - 2 piece', 'Good protein to calorie ratio. Low calorie. Fat percentage is high. Carbohdryate percentage is good. ', '14', '2', '32', '907', '21', '1', '0', '19', '289', '15'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '0', '1', '0', 'Fish Fillet', 'Low calorie. Fat percentage is high. Carbohdryate percentage is great! ', '14', '4', '49', '429', '25', '1', '1', '16', '291', '15'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '0', '1', '0', 'Jr. Roast Beef', 'Low calorie. Fat percentage is perfect! ', '6', '2', '25', '520', '25', '1', '3', '12', '210', '18'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '1', '1', '0', 'Classic Roast Beef Sandwich', 'Good protein to calorie ratio. Low calorie meal. Fat percentage is not bad. Carbohdryate percentage is not bad. ', '14', '6', '50', '950', '37', '2', '5', '22', '360', '15'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '0', '0', '0', 'Sausage, Egg &amp; Cheese Biscuit', 'Bad protein to calorie ratio. Carbohdryate percentage is low. Very high in sodium! ', '3', '11', '187', '1579', '30', '1', '3', '18', '557', '2'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '0', '0', '0', 'Sausage, Egg &amp; Cheese Sourdough', 'Bad protein to calorie ratio. Fat percentage is high. Carbohdryate percentage is good. High in sodium. ', '27', '8', '10', '1232', '40', '2', '5', '19', '514', '5'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '0', '1', '0', 'Sausage Biscuit', 'Bad protein to calorie ratio. Low calorie meal. Very high percentage of fat. Carbohdryate percentage is low. High in sodium. ', '31', '9', '32', '1160', '28', '1', '3', '10', '436', '1'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '0', '0', '0', 'Ham, Egg, &amp; Cheese Wrap', 'Not a good protein to calorie ratio. Fat percentage is high. Carbohdryate percentage is great! Very high in sodium! ', '31', '10', '183', '1929', '51', '2', '3', '24', '568', '7'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '0', '1', '0', 'Ham, Egg &amp; Cheese Croissant', 'Low calorie meal. Fat percentage is high. Carbohdryate percentage is low. High in sodium. ', '24', '10', '343', '1282', '25', '1', '4', '22', '434', '5'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '0', '1', '0', 'Ham Biscuit', 'Not a good protein to calorie ratio. Low calorie meal. Fat percentage is high. Carbohdryate percentage is good. High in sodium. ', '17', '4', '13', '1240', '29', '1', '4', '13', '316', '9'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '0', '1', '0', 'Blueberry Muffin', 'Bad protein to calorie ratio. Low calorie meal. Fat percentage is not bad. Carbohdryate percentage is high. High in sugar. ', '12', '2', '20', '490', '49', '1', '26', '4', '320', '2'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '0', '1', '0', 'Biscuit - Plain', 'Bad protein to calorie ratio. Low calorie. Fat percentage is high. Carbohdryate percentage is not bad. ', '15', '4', '1', '786', '28', '1', '3', '5', '273', '7'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '0', '1', '0', 'Bacon &amp; Egg Croissant', 'Bad protein to calorie ratio. Low calorie meal. Very high percentage of fat. Carbohdryate percentage is low. ', '22', '10', '187', '651', '23', '1', '3', '11', '337', '4'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '0', '0', '0', 'Roast Ham &amp; Swiss Sandwich', 'Fat percentage is a bit high. Carbohdryate percentage is not bad. Very high in sodium! ', '31', '8', '63', '2103', '75', '5', '19', '36', '705', '4'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '1', '1', '1', 'Corned Beef', 'Very high protein to calorie ratio! Calories are very low. Fat percentage is not bad. High in sodium. ', '5', '2', '50', '1313', '1', '0', '1', '18', '129', '18'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '0', '1', '0', 'Sesame Bun', 'Bad protein to calorie ratio. Calories are very low. Carbohdryate percentage is high. ', '2', '0', '0', '221', '22', '1', '4', '4', '127', '7'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '0', '1', '0', 'Sour Cream Baked Potato', 'Bad protein to calorie ratio. Low calorie meal. Fat percentage is great. Carbohdryate percentage is high. Low in sodium. ', '12', '7', '25', '50', '65', '6', '0', '8', '393', '12'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '0', '1', '0', 'Cinnamon Twist', 'Bad protein to calorie ratio. Low calorie. Fat percentage is high. Low in sodium. ', '14', '5', '5', '190', '33', '1', '11', '3', '260', '5'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '0', '1', '1', 'Sticky Bun Smear w/ pecans', 'Calories are very low. Very high percentage of fat. Carbohdryate percentage is good. Low in sodium. ', '11', '1', '0', '47', '18', '1', '14', '1', '181', '10'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '1', '1', '0', 'Market Fresh Mini Ham &amp; Cheese Sandwich', 'Good protein to calorie ratio. Low calorie. ', '5', '1', '23', '916', '28', '2', '6', '14', '228', '14'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '0', '1', '0', 'Chocolate Chip Cookie', 'Low calorie. Fat percentage is high. ', '10', '4', '15', '213', '26', '1', '16', '2', '202', '5'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '1', '0', '0', 'ArbysClean Roast Beef Max', 'Good protein to calorie ratio! Fat percentage is not bad. Carbohdryate percentage is great! Very high in sodium! ', '22', '9', '110', '1870', '49', '3', '6', '45', '580', '14'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '0', '0', '0', 'Smokehouse Brisket Sandwich', 'Fat percentage is high. Carbohdryate percentage is low. High in saturated fat! High in sodium. ', '35', '12', '110', '1230', '42', '3', '7', '35', '610', '4'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '1', '1', '1', 'Roast Chopped Farmhouse Salad', 'Perfect protein to calorie ratio! Low calorie. Fat percentage is high. ', '13', '7', '60', '780', '8', '3', '4', '23', '230', '14'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '1', '1', '0', 'Classic Roast Beef', 'Good protein to calorie ratio. Low calorie meal. Fat percentage is not bad. Carbohdryate percentage is good. ', '14', '5', '60', '970', '35', '1', '6', '23', '360', '15'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '0', '0', '0', 'Ham, Egg &amp; Cheese Sourdough', 'Under 700 calories. Fat percentage is high. Carbohdryate percentage is low. Very high in sodium! ', '35', '11', '354', '2104', '42', '2', '6', '34', '679', '3'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '0', '1', '0', 'Ham, Egg &amp; Cheese Biscuit', 'Not a good protein to calorie ratio. Low calorie meal. Fat percentage is high. Carbohdryate percentage is good. Very high in sodium! ', '23', '6', '169', '1658', '31', '1', '4', '20', '437', '6'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '0', '1', '0', 'Bacon, Egg &amp; Cheese Sourdough', 'Not a good protein to calorie ratio. Low calorie meal. Fat percentage is not bad. Carbohdryate percentage is good. High in sodium. ', '16', '5', '174', '1220', '40', '2', '5', '20', '437', '12'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '0', '1', '0', 'Bacon, Egg &amp; Cheese Biscuit', 'Bad protein to calorie ratio. Low calorie meal. Very high percentage of fat. Carbohdryate percentage is low. High in sodium. ', '28', '8', '169', '1446', '30', '1', '4', '17', '461', '3'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '0', '1', '0', 'French Toastix', 'Bad protein to calorie ratio. Low calorie meal. Fat percentage is a bit high. Lots of carbohdyrates. ', '13', '2', '0', '492', '44', '1', '11', '6', '312', '4'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '0', '1', '0', 'Egg &amp; Cheese Sourdough', 'Not a good protein to calorie ratio. Low calorie meal. Fat percentage is great. Carbohdryate percentage is not bad. High in sodium. ', '12', '3', '166', '1058', '40', '2', '5', '17', '392', '15'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '0', '1', '0', 'Sourdough Breakfast Bread', 'Bad protein to calorie ratio. Low calorie. Carbohdryate percentage is high. ', '5', '1', '0', '440', '38', '2', '4', '7', '230', '7'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '0', '1', '0', 'Breakfast Tortilla', 'Bad protein to calorie ratio. Low calorie. Carbohdryate percentage is high. ', '5', '1', '0', '557', '35', '1', '1', '6', '220', '5'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '0', '1', '0', 'Croissant', 'Bad protein to calorie ratio. Calories are very low. Fat percentage is high. Low in sodium. ', '10', '6', '30', '190', '21', '1', '2', '3', '190', '7'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '0', '1', '0', 'Swiss Melt', 'Low calorie meal. Fat percentage is not bad. ', '12', '4', '29', '919', '37', '2', '6', '16', '303', '13'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '0', '1', '0', 'BBQ Bacon \n Jack 2 for', 'Low calorie meal. Fat percentage is a bit high. High in sodium. ', '16', '5', '38', '1175', '42', '2', '10', '19', '360', '9'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '0', '1', '0', 'Sourdough Ham Melt', 'Low calorie meal. Fat percentage is good. Carbohdryate percentage is not bad. High in sodium. ', '13', '3', '31', '1280', '39', '2', '5', '19', '380', '15'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '0', '1', '0', 'Cheddar Fries - Medium', 'Bad protein to calorie ratio. Low calorie meal. Very high percentage of fat. Carbohdryate percentage is not bad. High in sodium. ', '28', '6', '2', '1311', '51', '5', '0', '6', '465', '6'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '1', '1', '1', 'Chicken Fillet Naturals', 'Great protein to calorie ratio! Low calorie. Fat percentage is high. ', '14', '2', '43', '507', '14', '1', '4', '24', '285', '13'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '0', '0', '1', 'Colby Jack Cheese Natural', 'Low in sodium. ', '7', '4', '20', '130', '0', '0', '0', '5', '800', '6'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '0', '1', '0', 'Chocolate Twist', 'Bad protein to calorie ratio. Low calorie. Fat percentage is high. Carbohdryate percentage is a little high. Low in sodium. ', '12', '4', '5', '110', '34', '2', '12', '4', '250', '5'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '0', '1', '1', 'TJ Icing', 'Calories are very low. Fat percentage is a bit high. Carbohdryate percentage is high. Low in sodium. ', '5', '2', '8', '50', '18', '0', '16', '1', '117', '5'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '1', '1', '0', 'Prime Cut Chicken Tenders', 'Good protein to calorie ratio! Low calorie meal. Fat percentage is high. Carbohdryate percentage is good. ', '17', '2', '45', '970', '25', '2', '0', '25', '350', '16'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '0', '1', '0', 'Curly Fries', 'Bad protein to calorie ratio. Low calorie. Fat percentage is high. ', '16', '2', '0', '676', '35', '3', '0', '3', '300', '9'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '1', '1', '0', 'Crispy Chopped Farmhouse Salad', 'Good protein to calorie ratio. Low calorie meal. Fat percentage is high. Carbohdryate percentage is low. High in sodium. ', '24', '9', '65', '1000', '26', '4', '5', '29', '430', '8'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '1', '1', '0', 'Grand Turkey Club', 'Good protein to calorie ratio! Low calorie meal. Fat percentage is good. Carbohdryate percentage is good. High in sodium. ', '13', '6', '65', '1360', '37', '2', '8', '29', '380', '17'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '1', '1', '1', 'Farmhouse Salad with Roast Turkey', 'Great protein to calorie ratio! Low calorie. Fat percentage is high. ', '13', '7', '60', '760', '10', '3', '5', '22', '240', '13'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '0', '1', '0', 'Jalapeno Bites ', 'Bad protein to calorie ratio. Low calorie meal. Fat percentage is high. Carbohdryate percentage is not bad. ', '25', '10', '45', '970', '49', '4', '4', '8', '460', '4'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '0', '1', '0', 'Beef n Cheddar Classic', 'Low calorie meal. Fat percentage is a bit high. Carbohdryate percentage is not bad. High in sodium. ', '18', '5', '45', '1290', '47', '2', '9', '23', '440', '9'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '0', '1', '0', 'Grand Turkey Club', 'Low calorie meal. Fat percentage is high. Carbohdryate percentage is good. High in sodium. ', '24', '8', '75', '1440', '38', '2', '8', '29', '490', '9'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '0', '0', '0', 'Shroom and Swiss', 'Not a good protein to calorie ratio. Fat percentage is high. Carbohdryate percentage is good. Very high in sodium! ', '25', '8', '60', '2350', '49', '3', '9', '24', '510', '5'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '0', '1', '0', 'Curly Fries', 'Bad protein to calorie ratio. Low calorie. Fat percentage is high. ', '13', '2', '0', '540', '28', '3', '0', '3', '240', '9'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '0', '0', '0', 'Prime-Cut Chicken Sandwich', 'Fat percentage is a bit high. Carbohdryate percentage is not bad. High in sodium. ', '22', '4', '50', '1110', '51', '4', '7', '26', '510', '10'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '0', '1', '0', 'Grand Turkey Club Sandwich', 'Low calorie meal. Fat percentage is high. Carbohdryate percentage is good. High in sodium. ', '24', '8', '75', '1440', '38', '2', '8', '29', '490', '9'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '0', '1', '0', 'Jalapeno Bites', 'Bad protein to calorie ratio. Low calorie. Fat percentage is high. ', '16', '6', '25', '610', '31', '2', '3', '5', '280', '6'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '1', '1', '0', 'Turkey Classic', 'Great protein to calorie ratio! Low calorie. Carbohdryate percentage is a little high. High in sodium. ', '5', '1', '40', '1020', '38', '2', '6', '24', '290', '13'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '1', '1', '0', 'Roast Turkey &amp; Swiss Wrap', 'Good protein to calorie ratio. Low calorie meal. Fat percentage is high. Carbohdryate percentage is good. Very high in sodium! ', '25', '6', '80', '1550', '39', '7', '6', '34', '490', '11'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '1', '0', '0', 'Angus Three Cheese &amp; Bacon', 'Good protein to calorie ratio! Fat percentage is not bad. Carbohdryate percentage is great! Very high in sodium! ', '21', '10', '95', '1610', '44', '2', '3', '40', '530', '14'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '1', '0', '0', 'Angus Three Cheese and Bacon', 'Good protein to calorie ratio. Fat percentage is high. Carbohdryate percentage is good. High in saturated fat! Very high in sodium! ', '33', '12', '105', '1820', '45', '2', '3', '41', '640', '5'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '0', '1', '0', 'Great Canadian - Roast Beef Sandwich', 'Not a good protein to calorie ratio. Low calorie meal. Fat percentage is high. Carbohdryate percentage is good. ', '21', '4', '35', '990', '40', '2', '11', '17', '410', '9'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '0', '1', '0', 'Steak House Onion Rings', 'Bad protein to calorie ratio. Low calorie meal. Fat percentage is high. Very high in sodium! ', '20', '3', '0', '1690', '51', '3', '6', '6', '410', '2'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '1', '1', '0', 'Turkey and Cheddar Classic', 'Good protein to calorie ratio. Low calorie meal. Fat percentage is great. High in sodium. ', '11', '2', '35', '1490', '46', '5', '10', '24', '380', '17'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '0', '0', '0', 'Crispy Onion Mighty Mini-Roast Beef', 'Not a good protein to calorie ratio. Fat percentage is high. Carbohdryate percentage is great! High in sodium. ', '30', '7', '55', '1260', '47', '2', '6', '23', '550', '9'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '0', '1', '0', 'Jr Roast Beef Sandwich', 'Low calorie. Fat percentage is perfect! ', '6', '2', '25', '520', '25', '1', '3', '12', '210', '18'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '0', '0', '0', 'Gyro', 'Not a good protein to calorie ratio. Fat percentage is high. Carbohdryate percentage is great! Very high in sodium! ', '32', '8', '60', '1500', '47', '3', '4', '25', '560', '8'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '0', '0', '0', 'Roast Beef Gyro', 'Not a good protein to calorie ratio. Fat percentage is high. Carbohdryate percentage is great! Very high in sodium! ', '32', '8', '60', '1500', '47', '3', '4', '25', '560', '8'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '0', '0', '0', 'Angus Cool Deli Sandwich', 'Fat percentage is high. Carbohdryate percentage is good. Very high in sodium! ', '35', '8', '80', '1760', '47', '3', '4', '37', '640', '6'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '1', '1', '0', 'Roast Beef Mid', 'Good protein to calorie ratio! Low calorie meal. Fat percentage is not bad. Carbohdryate percentage is good. High in sodium. ', '17', '6', '75', '1380', '40', '2', '5', '33', '440', '15'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '1', '1', '0', 'Roast Chicken Ranch Sandwich', 'Good protein to calorie ratio! Low calorie meal. Fat percentage is perfect! High in sodium. ', '10', '1', '50', '1030', '42', '3', '5', '26', '360', '19'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '0', '0', '0', 'Mushroom and Swiss', 'Not a good protein to calorie ratio. Fat percentage is high. Carbohdryate percentage is good. Very high in sodium! ', '25', '8', '60', '2350', '49', '3', '9', '24', '510', '5'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '0', '0', '0', 'Angus Philly', 'Fat percentage is high. Carbohdryate percentage is great! Very high in sodium! ', '29', '9', '85', '1760', '48', '3', '4', '34', '590', '8'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '1', '1', '0', 'Roast Chicken Club', 'Good protein to calorie ratio. Low calorie meal. Fat percentage is a bit high. Carbohdryate percentage is good. High in sodium. ', '19', '6', '70', '1440', '42', '2', '9', '30', '460', '11'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '1', '0', '0', 'Max Roast Beef Sandwich', 'Good protein to calorie ratio! Fat percentage is a bit high. Carbohdryate percentage is good. High in saturated fat! Very high in sodium! ', '29', '12', '120', '1830', '46', '3', '7', '43', '610', '8'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '0', '0', '0', 'Mushroom &amp; Swiss', 'Not a good protein to calorie ratio. Fat percentage is high. Carbohdryate percentage is good. Very high in sodium! ', '25', '8', '60', '2350', '49', '3', '9', '24', '510', '5'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '0', '1', '0', 'Value Curly Fries', 'Bad protein to calorie ratio. Low calorie. Fat percentage is high. ', '13', '2', '0', '540', '28', '3', '0', '3', '240', '9'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '0', '1', '0', 'ArbysClean Jr Chicken Sandwhich', 'Not a good protein to calorie ratio. Low calorie meal. Fat percentage is a bit high. Carbohdryate percentage is not bad. ', '15', '2', '25', '680', '33', '2', '4', '13', '320', '13'); "; 

 $sql .= "INSERT INTO ArbysClean (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('ArbysClean', '0', '0', '0', 'Turkey Asiago Sandwich', 'Fat percentage is a bit high. Carbohdryate percentage is not bad. Very high in sodium! ', '34', '8', '85', '1900', '77', '5', '17', '38', '760', '4'); "; 

 if (!$conn->multi_query($sql)) { echo "Error creating table: " . $conn->error;   } else { echo "it worked"; } $conn->close();?>