<?php $conn = new mysqli('db558054145.db.1and1.com', 'dbo558054145', 'fender123', 'db558054145'); if ($conn->connect_error) { die("connection failed:" . $conn->connect_error); } $sql = '';
 $sql .= "INSERT INTO restaurant (restName) VALUES ('McDonalds'); "; 

 $sql .= "CREATE TABLE McDonalds (`restName` varchar(30) COLLATE latin1_general_ci NOT NULL DEFAULT 'McDonalds', `High Protein` int(1) DEFAULT '0',     `Gluten Free` tinyint(1) DEFAULT '0', `Low Calorie` tinyint(1) DEFAULT '0', `Low Carbs` tinyint(1) DEFAULT '0',`mealName` varchar(50) COLLATE latin1_general_ci NOT NULL, `mealDesc` varchar(255) COLLATE latin1_general_ci DEFAULT NULL, `nutrFat` int(11), `nutrSatFat` int(11), `nutrChol` int(11), `nutrSodium` int(11), `nutrCarb` int(11), `nutrFiber` int(11), `nutrSugar` int(11), `nutrProtein` int(11), `nutrCal` int(11), `mealRating` int(11) DEFAULT NULL, `time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP); "; 

 $sql .= "INSERT INTO McDonalds (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('McDonalds', '0', '1', '0', 'Egg McMuffin', 'Low calorie. Fat percentage is a bit high. Carbohdryate percentage is not bad. ', '12', '5', '260', '0', '31', '4', '3', '17', '290', '13'); "; 

 $sql .= "INSERT INTO McDonalds (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('McDonalds', '0', '1', '0', 'Cheeseburger', 'Low calorie. Fat percentage is a bit high. ', '12', '6', '40', '0', '33', '2', '7', '15', '300', '12'); "; 

 $sql .= "INSERT INTO McDonalds (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('McDonalds', '0', '1', '0', 'Hamburger', 'Low calorie. Fat percentage is not bad. ', '9', '3', '25', '0', '32', '1', '6', '13', '255', '13'); "; 

 $sql .= "INSERT INTO McDonalds (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('McDonalds', '1', '1', '1', 'Premium Caesar Salad with Grilled Chicken', 'Very high protein to calorie ratio! Calories are very low. Fat percentage is perfect! Carbohdryate percentage is low. ', '5', '3', '70', '0', '10', '4', '5', '27', '190', '23'); "; 

 $sql .= "INSERT INTO McDonalds (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('McDonalds', '1', '1', '0', 'Premium Southwest Salad', 'Great protein to calorie ratio! Low calorie. Fat percentage is perfect! Carbohdryate percentage is good. ', '8', '2', '70', '0', '28', '7', '11', '27', '290', '26'); "; 

 $sql .= "INSERT INTO McDonalds (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('McDonalds', '0', '1', '0', 'Sausage Burrito', 'Not a good protein to calorie ratio. Low calorie. Fat percentage is high. Carbohdryate percentage is great! ', '16', '7', '115', '0', '26', '1', '2', '12', '300', '12'); "; 

 $sql .= "INSERT INTO McDonalds (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('McDonalds', '0', '1', '0', 'Filet-O-Fish', 'Low calorie. Fat percentage is great. Lots of carbohdyrates. ', '8', '1', '25', '0', '38', '1', '5', '14', '270', '13'); "; 

 $sql .= "INSERT INTO McDonalds (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('McDonalds', '1', '1', '1', 'Bacon Ranch Salad with Grilled Chicken', 'Very high protein to calorie ratio! Low calorie. Fat percentage is not bad. ', '10', '4', '110', '0', '10', '3', '5', '34', '260', '19'); "; 

 $sql .= "INSERT INTO McDonalds (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('McDonalds', '1', '1', '0', 'Premium Grilled Chicken Classic Sandwich', 'Great protein to calorie ratio! Low calorie meal. Fat percentage is perfect! ', '9', '2', '65', '0', '42', '3', '8', '28', '350', '20'); "; 

 $sql .= "INSERT INTO McDonalds (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('McDonalds', '1', '1', '1', 'Grilled Chicken Caesar Salad', 'Very high protein to calorie ratio! Calories are very low. Fat percentage is perfect! Carbohdryate percentage is low. ', '5', '3', '70', '0', '10', '4', '5', '27', '190', '23'); "; 

 $sql .= "INSERT INTO McDonalds (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('McDonalds', '0', '1', '1', 'Chicken McNuggets', 'Calories are very low. Very high percentage of fat. Carbohdryate percentage is low. ', '12', '2', '30', '0', '11', '0', '0', '10', '190', '11'); "; 

 $sql .= "INSERT INTO McDonalds (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('McDonalds', '1', '1', '1', 'Grilled Chicken Bacon Ranch Salad', 'Very high protein to calorie ratio! Calories are very low. Fat percentage is not bad. ', '9', '4', '85', '0', '10', '4', '5', '30', '230', '19'); "; 

 $sql .= "INSERT INTO McDonalds (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('McDonalds', '0', '1', '0', 'McDouble', 'Low calorie meal. Fat percentage is high. Carbohdryate percentage is great! ', '19', '8', '65', '0', '33', '2', '8', '23', '390', '13'); "; 

 $sql .= "INSERT INTO McDonalds (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('McDonalds', '0', '1', '0', 'Ranch Snack Wrap', 'Low calorie. Fat percentage is a bit high. Carbohdryate percentage is good. ', '12', '4', '45', '0', '25', '1', '2', '16', '270', '14'); "; 

 $sql .= "INSERT INTO McDonalds (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('McDonalds', '1', '1', '0', 'McDonalds Asian grilled chicken salad', 'Perfect protein to calorie ratio! Low calorie. Fat percentage is good. Carbohdryate percentage is good. ', '10', '1', '65', '0', '23', '5', '12', '32', '300', '25'); "; 

 $sql .= "INSERT INTO McDonalds (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('McDonalds', '0', '1', '0', 'Quarter Pounder', 'Low calorie meal. Fat percentage is a bit high. Carbohdryate percentage is good. ', '18', '6', '63', '0', '37', '2', '8', '23', '410', '12'); "; 

 $sql .= "INSERT INTO McDonalds (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('McDonalds', '1', '1', '0', 'Chicken Fajita', 'Good protein to calorie ratio. Calories are very low. Fat percentage is good. ', '6', '2', '30', '0', '21', '1', '0', '11', '180', '18'); "; 

 $sql .= "INSERT INTO McDonalds (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('McDonalds', '1', '1', '0', 'Bacon Ranch Salad with Crispy Chicken', 'Good protein to calorie ratio! Low calorie meal. Fat percentage is high. ', '23', '0', '105', '0', '20', '4', '8', '31', '410', '12'); "; 

 $sql .= "INSERT INTO McDonalds (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('McDonalds', '0', '1', '0', 'Ranch Snack Wrap', 'Low calorie. Fat percentage is a bit high. Carbohdryate percentage is great! ', '12', '4', '47', '0', '25', '1', '2', '16', '279', '16'); "; 

 $sql .= "INSERT INTO McDonalds (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('McDonalds', '0', '1', '0', 'Big N Tasty', 'Low calorie meal. Fat percentage is high. Carbohdryate percentage is great! ', '24', '8', '70', '0', '37', '3', '8', '24', '460', '12'); "; 

 $sql .= "INSERT INTO McDonalds (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('McDonalds', '1', '1', '0', 'Honey Mustard Snack Wrap (Grilled)', 'Good protein to calorie ratio. Low calorie. Fat percentage is good. Carbohdryate percentage is not bad. ', '9', '3', '45', '0', '27', '1', '4', '18', '260', '17'); "; 

 $sql .= "INSERT INTO McDonalds (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('McDonalds', '1', '1', '0', 'Premium Grilled Chicken Ranch BLT Sandwich', 'Great protein to calorie ratio! Low calorie meal. Fat percentage is perfect! ', '10', '3', '75', '0', '42', '3', '9', '31', '380', '19'); "; 

 $sql .= "INSERT INTO McDonalds (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('McDonalds', '0', '1', '1', 'Chicken McNuggets', 'Calories are very low. Very high percentage of fat. Carbohdryate percentage is low. ', '10', '2', '25', '0', '10', '0', '0', '10', '170', '11'); "; 

 $sql .= "INSERT INTO McDonalds (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('McDonalds', '1', '1', '0', 'Chipotle BBQ Snack Wrap (Grilled)', 'Good protein to calorie ratio. Low calorie. Fat percentage is good. Carbohdryate percentage is not bad. ', '9', '3', '45', '0', '28', '1', '5', '18', '260', '17'); "; 

 $sql .= "INSERT INTO McDonalds (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('McDonalds', '0', '0', '0', 'Premium Crispy Chicken Classic Sandwich', 'Fat percentage is not bad. ', '20', '3', '50', '0', '59', '3', '12', '28', '530', '11'); "; 

 $sql .= "INSERT INTO McDonalds (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('McDonalds', '1', '1', '0', 'Chicken McGrill', 'Good protein to calorie ratio. Low calorie meal. Fat percentage is a bit high. Carbohdryate percentage is good. ', '17', '3', '60', '0', '39', '3', '7', '25', '410', '14'); "; 

 $sql .= "INSERT INTO McDonalds (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('McDonalds', '1', '0', '0', 'Premium Grilled Chicken Club Sandwich', 'Good protein to calorie ratio! Fat percentage is not bad. Carbohdryate percentage is great! ', '21', '7', '112', '0', '46', '3', '9', '42', '542', '16'); "; 

 $sql .= "INSERT INTO McDonalds (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('McDonalds', '1', '1', '0', 'Egg White Delight', 'Good protein to calorie ratio. Calories are very low. Fat percentage is great. ', '7', '2', '22', '0', '26', '3', '2', '15', '219', '19'); "; 

 $sql .= "INSERT INTO McDonalds (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('McDonalds', '1', '1', '0', 'McVeggie Burger on Whole Wheat Bun', 'Good protein to calorie ratio. Low calorie meal. ', '8', '1', '0', '0', '49', '11', '11', '22', '360', '12'); "; 

 $sql .= "INSERT INTO McDonalds (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('McDonalds', '1', '1', '0', 'Premium Southwest Salad with Crispy Chicken', 'Good protein to calorie ratio. Low calorie meal. Fat percentage is a bit high. Carbohdryate percentage is great! ', '20', '4', '55', '0', '38', '6', '12', '26', '430', '17'); "; 

 $sql .= "INSERT INTO McDonalds (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('McDonalds', '1', '1', '0', 'Premium Southwest Salad with Grilled Chicken', 'Good protein to calorie ratio! Low calorie meal. Fat percentage is not bad. Carbohdryate percentage is not bad. ', '14', '3', '90', '0', '39', '7', '14', '28', '390', '17'); "; 

 $sql .= "INSERT INTO McDonalds (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('McDonalds', '1', '1', '0', 'Southern Style Crispy Chicken Sandwich', 'Good protein to calorie ratio. Low calorie meal. Fat percentage is a bit high. Carbohdryate percentage is good. ', '17', '3', '45', '0', '39', '1', '6', '24', '400', '14'); "; 

 $sql .= "INSERT INTO McDonalds (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('McDonalds', '1', '1', '0', 'Egg White Delight McMuffin', 'Good protein to calorie ratio! Calories are very low. Fat percentage is perfect! ', '7', '3', '25', '0', '32', '5', '3', '18', '250', '21'); "; 

 $sql .= "INSERT INTO McDonalds (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('McDonalds', '1', '1', '0', 'Crispy Chicken Bacon Ranch Salad', 'Good protein to calorie ratio! Low calorie meal. Fat percentage is high. Carbohdryate percentage is low. ', '21', '7', '65', '0', '20', '3', '4', '26', '370', '11'); "; 

 $sql .= "INSERT INTO McDonalds (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('McDonalds', '1', '1', '0', 'Premium Caesar Salad with Crispy Chicken', 'Good protein to calorie ratio! Low calorie meal. Fat percentage is high. Carbohdryate percentage is low. ', '17', '4', '60', '0', '20', '3', '6', '26', '330', '13'); "; 

 $sql .= "INSERT INTO McDonalds (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('McDonalds', '0', '1', '0', 'Grilled Chicken Flatbread Sandwich', 'Low calorie meal. Fat percentage is great. ', '12', '2', '35', '0', '52', '4', '5', '21', '390', '14'); "; 

 $sql .= "INSERT INTO McDonalds (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('McDonalds', '1', '1', '0', 'Crispy Chicken Caesar Salad', 'Good protein to calorie ratio! Low calorie meal. Fat percentage is high. Carbohdryate percentage is low. ', '16', '4', '50', '0', '20', '3', '4', '23', '310', '13'); "; 

 $sql .= "INSERT INTO McDonalds (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('McDonalds', '1', '1', '1', 'Grilled Chicken California Cobb Salad', 'Perfect protein to calorie ratio! Low calorie. Fat percentage is high. ', '14', '6', '130', '0', '11', '3', '4', '30', '280', '14'); "; 

 $sql .= "INSERT INTO McDonalds (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('McDonalds', '0', '1', '1', 'Big Mac', 'Not a good protein to calorie ratio. Calories are very low. Fat percentage is high. Carbohdryate percentage is great! ', '9', '2', '22', '0', '15', '1', '0', '8', '179', '15'); "; 

 $sql .= "INSERT INTO McDonalds (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('McDonalds', '1', '1', '1', 'Crispy Chicken', 'Good protein to calorie ratio. Calories are very low. Fat percentage is high. Carbohdryate percentage is low. ', '14', '2', '45', '0', '15', '1', '2', '16', '250', '13'); "; 

 $sql .= "INSERT INTO McDonalds (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('McDonalds', '1', '1', '0', 'Premium McWrap Chicken Sweet Chili Grilled', 'Good protein to calorie ratio! Low calorie meal. Fat percentage is perfect! ', '9', '4', '65', '0', '43', '2', '9', '26', '360', '18'); "; 

 $sql .= "INSERT INTO McDonalds (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('McDonalds', '1', '1', '1', 'Premium Bacon Ranch Salad with Grilled Chicken', 'Very high protein to calorie ratio! Low calorie. Fat percentage is good. Carbohdryate percentage is low. ', '9', '4', '90', '0', '13', '3', '5', '33', '260', '21'); "; 

 $sql .= "INSERT INTO McDonalds (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('McDonalds', '1', '1', '0', 'Premium Southwest Salad with Grilled Chicken', 'Great protein to calorie ratio! Low calorie meal. Fat percentage is good. Carbohdryate percentage is great! ', '11', '4', '95', '0', '28', '7', '10', '32', '340', '24'); "; 

 $sql .= "INSERT INTO McDonalds (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('McDonalds', '1', '1', '0', 'McLean Deluxe', 'Good protein to calorie ratio! Low calorie meal. Fat percentage is not bad. Carbohdryate percentage is not bad. ', '12', '4', '60', '0', '37', '2', '8', '24', '340', '17'); "; 

 $sql .= "INSERT INTO McDonalds (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('McDonalds', '0', '1', '0', 'Chipotle BBQ Snack Wrap (Crispy)', 'Not a good protein to calorie ratio. Low calorie meal. Fat percentage is a bit high. Carbohdryate percentage is not bad. ', '15', '4', '30', '0', '35', '1', '4', '14', '330', '11'); "; 

 $sql .= "INSERT INTO McDonalds (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('McDonalds', '1', '1', '1', 'California Cobb Salad', 'Good protein to calorie ratio. Calories are very low. Fat percentage is high. Carbohdryate percentage is low. ', '9', '4', '85', '0', '9', '4', '5', '11', '160', '12'); "; 

 $sql .= "INSERT INTO McDonalds (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('McDonalds', '0', '1', '0', 'Honey Mustard Snack Wrap', 'Not a good protein to calorie ratio. Low calorie meal. Fat percentage is a bit high. Carbohdryate percentage is good. ', '15', '4', '31', '0', '33', '1', '2', '14', '336', '12'); "; 

 $sql .= "INSERT INTO McDonalds (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('McDonalds', '0', '0', '0', 'Premium Crispy Chicken Ranch BLT Sandwich', 'Fat percentage is not bad. Carbohdryate percentage is not bad. ', '23', '4', '60', '0', '61', '3', '14', '32', '580', '11'); "; 

 $sql .= "INSERT INTO McDonalds (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('McDonalds', '1', '1', '0', 'Premium Bacon Ranch Salad with Crispy Chicken', 'Good protein to calorie ratio! Low calorie meal. Fat percentage is high. Carbohdryate percentage is low. ', '20', '6', '75', '0', '20', '3', '6', '29', '370', '11'); "; 

 $sql .= "INSERT INTO McDonalds (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('McDonalds', '1', '1', '1', 'Premium Grilled Chicken Sandwich', 'Very high protein to calorie ratio! Calories are very low. Fat percentage is a bit high. ', '8', '1', '70', '0', '5', '0', '2', '24', '180', '17'); "; 

 $sql .= "INSERT INTO McDonalds (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('McDonalds', '0', '1', '0', 'Double Hamburger', 'Low calorie meal. Fat percentage is a bit high. Carbohdryate percentage is good. ', '18', '7', '66', '0', '37', '2', '7', '23', '407', '12'); "; 

 $sql .= "INSERT INTO McDonalds (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('McDonalds', '1', '1', '0', 'California Cobb Salad with Crispy Chicken', 'Great protein to calorie ratio! Low calorie meal. Fat percentage is high. Carbohdryate percentage is low. ', '18', '6', '130', '0', '22', '4', '5', '30', '360', '13'); "; 

 $sql .= "INSERT INTO McDonalds (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('McDonalds', '0', '1', '0', 'Grilled Onion Cheddar Burger', 'Not a good protein to calorie ratio. Low calorie meal. Fat percentage is a bit high. Carbohdryate percentage is not bad. ', '13', '6', '46', '0', '32', '2', '6', '15', '308', '11'); "; 

 $sql .= "INSERT INTO McDonalds (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('McDonalds', '1', '1', '0', 'McVeggie Burger on Whole Wheat Bun with Cheese', 'Good protein to calorie ratio. Low calorie meal. Fat percentage is great. ', '12', '4', '15', '0', '50', '11', '11', '25', '410', '16'); "; 

 $sql .= "INSERT INTO McDonalds (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('McDonalds', '1', '1', '0', 'Grilled Chicken Snack Wrap', 'Good protein to calorie ratio. Calories are very low. Fat percentage is good. Carbohdryate percentage is not bad. ', '8', '3', '40', '0', '24', '1', '2', '16', '231', '17'); "; 

 $sql .= "INSERT INTO McDonalds (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('McDonalds', '1', '1', '0', 'Egg White Delight McMuffin', 'Good protein to calorie ratio! Calories are very low. Fat percentage is perfect! ', '7', '3', '25', '0', '30', '4', '3', '18', '250', '19'); "; 

 $sql .= "INSERT INTO McDonalds (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('McDonalds', '0', '1', '0', 'Sweet Chilli Crispy Chicken Wrap', 'Not a good protein to calorie ratio. Low calorie meal. Fat percentage is not bad. ', '18', '3', '0', '0', '53', '3', '8', '20', '460', '12'); "; 

 $sql .= "INSERT INTO McDonalds (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('McDonalds', '0', '1', '1', 'McChicken Patty', 'Calories are very low. Fat percentage is high. Carbohdryate percentage is low. ', '9', '1', '30', '0', '10', '0', '0', '9', '160', '13'); "; 

 $sql .= "INSERT INTO McDonalds (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('McDonalds', '1', '1', '0', 'McLean Deluxe with Cheese', 'Good protein to calorie ratio. Low calorie meal. Fat percentage is a bit high. Carbohdryate percentage is good. ', '16', '7', '70', '0', '38', '2', '8', '26', '400', '14'); "; 

 $sql .= "INSERT INTO McDonalds (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('McDonalds', '1', '1', '0', 'Grilled Chicken and Bacon Premium McWrap', 'Good protein to calorie ratio! Low calorie meal. Fat percentage is not bad. Carbohdryate percentage is great! ', '16', '6', '91', '0', '40', '3', '5', '33', '445', '18'); "; 

 $sql .= "INSERT INTO McDonalds (restName, `High Protein`, `Low Calorie`, `Low Carbs`, mealName, mealDesc, nutrFat, nutrSatFat, nutrChol, nutrSodium, nutrCarb, nutrFiber, nutrSugar, nutrProtein, nutrCal, mealRating) VALUES ('McDonalds', '0', '0', '0', 'Steak Burrito', 'Fat percentage is a bit high. Carbohdryate percentage is good. ', '32', '0', '0', '0', '67', '3', '0', '37', '703', '12'); "; 

 if (!$conn->multi_query($sql)) { echo "Error creating table: " . $conn->error;   } else { echo "it worked"; } $conn->close();?>